#!/bin/bash

cd `dirname $0`
cd ..
rm -rf classes/*

CLASSPATH="classes:src"

for f in $HOME/.clojure/*; do
   if [ -d $f ]; then
     CLASSPATH="$CLASSPATH:$f/*"
   else
     CLASSPATH="$CLASSPATH:$f"
   fi
done

java -cp $CLASSPATH clojure.main -e "(compile 'com.leftrightfold.trixx)"
jar cf trixx.jar -C classes .
